language: node_js

node_js:
  - '6.9.2'

install:
  # Install npm dependecies
  # Note: "npm install" also runs "npm prepublish"
  - npm install

before_script:
  # Install external definitions
  # this is not needed because npm install runs also prepublish where we install typings
  # - npm run typings:install

script:
  - npm test
